version: "3.5"
services:
  motte:
    build: ./motte
    restart: unless-stopped
    volumes:
      - ./uploads:/usr/src/uploads
  restapi:
    build: ./restapi
    restart: unless-stopped
    volumes:
      - ./uploads:/usr/src/uploads
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginxRest/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/ssl:/etc/nginx/ssl