version: "3.5"
services:
  regis:
    image: registry:2
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /ssl/cert.pem
      REGISTRY_HTTP_TLS_KEY: /ssl/fullchain.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - regisdata:/data
      - ./etc/regis/ssl:/ssl
  motte:
    build: ./motte
    restart: unless-stopped
    volumes:
      - ./uploads:/usr/src/uploads
  gqlapi:
    build: ./gqlapi
    restart: unless-stopped
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./zapql/build:/usr/share/nginx/html
      - ./etc/nginxGql/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/ssl:/etc/nginx/ssl
volumes:
  regisdata:
    external: true